<Project>
  <!-- Project properties -->
  <PropertyGroup>
    <LangVersion>14</LangVersion>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <!-- NuGet -->
  <PropertyGroup>
    <Authors>Photinizer</Authors>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <Copyright>Copyright (c) $(Authors) $([System.DateTime]::Today.ToString(yyyy))</Copyright>
  </PropertyGroup>

</Project>