<Project>
  <!-- Project properties -->
  <PropertyGroup>
    <LangVersion>14</LangVersion>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <!-- NuGet -->
  <PropertyGroup>
    <Authors>Photinizer</Authors>
    <Copyright>Copyright (c) $(Authors) $([System.DateTime]::Today.ToString(yyyy))</Copyright>
    <PackageLicenseExpression>Apache-2.0</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/Photinizer/Photinizer</PackageProjectUrl>
  </PropertyGroup>

  <!-- SourceLink -->
  <PropertyGroup>
    <!-- Optional: Publish the repository URL in the built .nupkg (in the NuSpec <Repository> element) -->
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <!-- Optional: Embed source files that are not tracked by the source control manager in the PDB -->
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <!-- Optional: Build symbol package (.snupkg) to distribute the PDB containing Source Link -->
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

</Project>