<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Exe</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <IncludeSymbols>false</IncludeSymbols>
    <DevelopmentDependency>true</DevelopmentDependency>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <SuppressDependenciesWhenPacking>true</SuppressDependenciesWhenPacking>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>logo.png</PackageIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Photinizer\Settings\PhotinizerConfiguration.cs" Link="Shared\PhotinizerConfiguration.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.4" />
  </ItemGroup>

  <ItemGroup>
    <None Include="buildTransitive\Photinizer.Cli.props" Pack="true" PackagePath="buildTransitive\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="$(OutputPath)Photinizer.Cli.dll" Condition="Exists('$(OutputPath)Photinizer.Cli.dll')" Pack="true" PackagePath="tools/$(TargetFramework)/any" />
    <None Include="$(OutputPath)Photinizer.Cli.runtimeconfig.json" Condition="Exists('$(OutputPath)Photinizer.Cli.runtimeconfig.json')" Pack="true" PackagePath="tools/$(TargetFramework)/any" />
    <None Include="$(OutputPath)Photinizer.Cli.deps.json" Condition="Exists('$(OutputPath)Photinizer.Cli.deps.json')" Pack="true" PackagePath="tools/$(TargetFramework)/any" />
    <None Include="$(OutputPath)*.dll" Exclude="$(OutputPath)Photinizer.Cli.dll" Pack="true" PackagePath="tools/$(TargetFramework)/any" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\assets\logo.png" Pack="true" PackagePath="\" />
    <None Include=".\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
